### ISSUE TITLE
modsi3: debug assertion

### ISSUE THREAD

**Issue by japaric** [rust-lang-nursery/compiler-builtins#151]
``` rust
#[test]
fn modsi3() {
    let (a, b) = (-2147483648, 1798783296);
    let c_ = __modsi3(a, b);
}
```

```
running 1 test
test modsi3 ... FAILED

failures:

---- modsi3 stdout ----
        thread 'modsi3' panicked at 'attempt to subtract with overflow', /home/japaric/.cargo/git/checkouts/compiler-builtins-ec094dc45a0179c8/9681358/src/int/sdiv.rs:38
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    modsi3

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured

error: test failed
```

**Comment by japaric** [comment]
Similar error: `moddi3` with `(4173728065815314432, -9223372036854775808)`

```
running 1 test
test moddi3 ... FAILED

failures:

---- moddi3 stdout ----
        thread 'moddi3' panicked at 'attempt to subtract with overflow', /home/japaric/.cargo/git/checkouts/compiler-builtins-ec094dc45a0179c8/9681358/src/int/sdiv.rs:36
note: Run with `RUST_BACKTRACE=1` for a backtrace.


failures:
    moddi3

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured
```
